export const preferenceAbbreviations = {
  CF: "Carpets",
  GF: "gym",
  RF: "raised",
  SF: "sports",
  WF: "Wooden",
  PF: "PVC",
  PL: "Plain",
  TX: "Textured",
  PT: "Patterned",
  STP: "Stripped",
  FLK: "Flokati",
  SHG: "Shag",
  BER: "Berber",
  CBL: "Cable",
  FRZ: "Frieze",
  CC: "CustomColor",
  PP: "polypropylene",
  NY: "Nylon",
  SS: "Sisal",
  WL: "Wool",
  BG: "Beige",
  BR: "Brown",
  GY: "Grey",
  GD: "Gold",
  GN: "Green",
  BL: "Blue",
  WH: "White",
  BK: "Black",
  TN: "Tan",
  RS: "Rose",
  WW: "Wall to Wall",
  CT: "Carpet Tiles",
  AR: "Area Rugs",
  RN: "Runners",
  CG: "Carpet Grass",
  OL: "Overlay Carpet",
  CA: "Cardio",
  MT: "Machine Training",
  FW: "Free Weights",
  FT: "Functional Training",
  DC: "Dance",
  AE: "Aerobic",
  ZB: "Zumba",
  STP: "Step",
  TRX: "TRX",
  PLT: "Pilates",
  WL: "Weightlifting",
  PLF: "Powerlifting",
  JD: "Judo",
  KB: "Kickboxing",
  KT: "Karate",
  BX: "Boxing",
  TKD: "Taekwondo",
  AKD: "Akido",
  FIT: "fitness",
  GT: "group training",
  STR: "strength",
  MA: "martial arts",
  SV: "Value",
  SE: "Essential",
  SP: "Premier",
  SS: "Signature",
  EL: "Elite",
  DBR: "Dark Brown",
  RD: "Red",
  MF: "Matt Finish",
  GF: "Gloss Finish",
  RG: "Rubber",
  LV: "Luxury Vinyl",
  WV: "Woven Vinyl",
  AB: "Abstract",
  WE: "Wood Effect",
  SH: "Sheet",
  TP: "Tile",
  PLK: "Plank",
  MC: "Multicolor",
  SRM: "Server Rooms",
  TRM: "Telecom Rooms",
  OFF: "Offices",
  RTL: "Retail",
  HOS: "Hospitality",
  PA: "Public Area",
  IF: "Industrial Facilities",
  FP: "Food Processing",
  CL: "Chemical Lab",
  CR: "Clean Rooms",
  FR: "Facility Rooms",
  SC: "Schools",
  KT: "Kitchens",
  BS: "Basements",
  SW: "Swimming",
  DC: "Data Center",
  CM: "Commercial",
  IN: "Industry",
  HC: "Healthcare",
  ACT: "Activities",
  OT: "Others",
};
